---
#Debian12/Ubuntu22 Tested
#Docker is required!
- name: Run XMRig Container
  hosts: all
  become: true
  tasks:
    - name: Install msr-tools and enable msr module
      block:
        - name: Install msr-tools
          ansible.builtin.package:
            name: msr-tools
            state: present

        - name: Enable msr module
          ansible.builtin.modprobe:
            name: msr
            state: present

    - name: Enable 1GB hugepages
      shell: |
        sysctl -w vm.nr_hugepages=$(nproc)
        for i in $(find /sys/devices/system/node/node* -maxdepth 0 -type d);
        do
          echo 3 > "$i/hugepages/hugepages-1048576kB/nr_hugepages";
        done
        echo "1GB pages successfully enabled"
      args:
        executable: /bin/bash

    - name: Allow MSR writes and apply best MSR settings for CPU
      shell: |
        MSR_FILE=/sys/module/msr/parameters/allow_writes

        if test -e "$MSR_FILE"; then
          echo on > $MSR_FILE
        else
          modprobe msr allow_writes=on
        fi

        if grep -E 'AMD Ryzen|AMD EPYC' /proc/cpuinfo > /dev/null; then
          if grep "cpu family[[:space:]]\{1,\}:[[:space:]]25" /proc/cpuinfo > /dev/null; then
            if grep "model[[:space:]]\{1,\}:[[:space:]]97" /proc/cpuinfo > /dev/null; then
              echo "Detected Zen4 CPU"
              wrmsr -a 0xc0011020 0x4400000000000
              wrmsr -a 0xc0011021 0x4000000000040
              wrmsr -a 0xc0011022 0x8680000401570000
              wrmsr -a 0xc001102b 0x2040cc10
              echo "MSR register values for Zen4 applied"
            else
              echo "Detected Zen3 CPU"
              wrmsr -a 0xc0011020 0x4480000000000
              wrmsr -a 0xc0011021 0x1c000200000040
              wrmsr -a 0xc0011022 0xc000000401570000
              wrmsr -a 0xc001102b 0x2000cc10
              echo "MSR register values for Zen3 applied"
            fi
          else
            echo "Detected Zen1/Zen2 CPU"
            wrmsr -a 0xc0011020 0
            wrmsr -a 0xc0011021 0x40
            wrmsr -a 0xc0011022 0x1510000
            wrmsr -a 0xc001102b 0x2000cc16
            echo "MSR register values for Zen1/Zen2 applied"
          fi
        elif grep "Intel" /proc/cpuinfo > /dev/null; then
          echo "Detected Intel CPU"
          wrmsr -a 0x1a4 0xf
          echo "MSR register values for Intel applied"
        else
          echo "No supported CPU detected"
        fi
      args:
        executable: /bin/sh

    - name: Pull the XMRig Docker image
      docker_image:
        name: cryptoandcoffee/akash-xmrig:40
        source: pull

    - name: Run XMRig Docker container
      docker_container:
        name: miner-xmrig
        image: cryptoandcoffee/akash-xmrig:40
        state: started
        restart_policy: always
        privileged: true
        cpus: 8
        memory: 4.75g
        env:
          ALGO: "rx/0"
          POOL: "gulf.moneroocean.stream:20032"
          WALLET: ""
          WORKER: "{{ inventory_hostname }}"
          PASS: "x"
          TLS: "true"
          TLS_FINGERPRINT: ""
          RANDOMX_MODE: "fast"
          CUSTOM_OPTIONS: "--randomx-1gb-pages"
          AKASH_PROVIDER_STARTUP_CHECK: "false"
